"""
tasks/obsidian_writer.py  —  Task 2b
Writes lesson notes as Markdown into your Obsidian vault.
Also maintains a daily progress index file.
"""
import os
from datetime import date
from config import OBSIDIAN_VAULT
from utils.db import get_total_xp, get_level, get_conn


def ensure_dirs():
    for sub in ["lessons", "daily"]:
        os.makedirs(os.path.join(OBSIDIAN_VAULT, sub), exist_ok=True)


def save_note(topic: str, lesson_num: int, lesson_title: str, content: str):
    """Write a lesson note to the Obsidian vault."""
    ensure_dirs()
    today = str(date.today())
    safe_title = lesson_title.replace("/", "-").replace(" ", "_")[:50]
    filename = f"{topic}_L{lesson_num:02d}_{safe_title}.md"
    path = os.path.join(OBSIDIAN_VAULT, "lessons", filename)

    note = f"""---
topic: {topic}
lesson: {lesson_num}
date: {today}
tags: [datacharizard, {topic}, learning]
---

# Lesson {lesson_num}: {lesson_title}

{content}

---
*Generated by DataCharizard 🔥 — {today}*
"""
    with open(path, "w") as f:
        f.write(note)
    print(f"  📓 Obsidian note saved: lessons/{filename}")
    update_daily_index()


def update_daily_index():
    """Regenerate the daily index note with all today's activity."""
    ensure_dirs()
    today = str(date.today())
    xp = get_total_xp()
    level = get_level(xp)

    # Get today's lessons
    with get_conn() as conn:
        lessons = conn.execute(
            "SELECT topic, lesson_num FROM user_progress WHERE date_done=?", (today,)
        ).fetchall()
        quizzes = conn.execute(
            "SELECT COUNT(*) as n, SUM(correct) as c, SUM(xp_earned) as xp "
            "FROM quiz_results WHERE date_done=?", (today,)
        ).fetchone()

    lesson_lines = "\n".join(
        f"- [[{r['topic']}_L{r['lesson_num']:02d}]] — {r['topic']} lesson {r['lesson_num']}"
        for r in lessons
    ) or "- No lessons completed yet today"

    quiz_line = (f"- {quizzes['n']} questions · {quizzes['c']} correct "
                 f"· +{quizzes['xp'] or 0} XP"
                 if quizzes and quizzes["n"] else "- No quiz today")

    index_content = f"""---
date: {today}
type: daily-index
xp_total: {xp}
level: "{level}"
tags: [datacharizard, daily, index]
---

# DataCharizard — {today}

## 🔥 Level progress
- **Level**: {level}
- **Total XP**: {xp}

## 📚 Lessons today
{lesson_lines}

## 🎯 Quiz results today
{quiz_line}

## 🔗 Quick links
- [[DataCharizard Index]] — all-time progress
- [[lessons/]] — all lesson notes

---
*Auto-updated by DataCharizard*
"""
    path = os.path.join(OBSIDIAN_VAULT, "daily", f"{today}.md")
    with open(path, "w") as f:
        f.write(index_content)
    print(f"  📓 Daily index updated: daily/{today}.md")


def rebuild_master_index():
    """Create/update the master DataCharizard Index note."""
    ensure_dirs()
    xp = get_total_xp()
    level = get_level(xp)

    with get_conn() as conn:
        all_days = conn.execute(
            "SELECT DISTINCT date_done FROM user_progress ORDER BY date_done DESC"
        ).fetchall()
        total_lessons = conn.execute(
            "SELECT COUNT(*) FROM user_progress WHERE completed=1"
        ).fetchone()[0]
        total_quizzes = conn.execute("SELECT COUNT(*) FROM quiz_results").fetchone()[0]
        accuracy = conn.execute(
            "SELECT ROUND(AVG(correct)*100,0) FROM quiz_results"
        ).fetchone()[0] or 0

    day_links = "\n".join(f"- [[daily/{r[0]}]] — {r[0]}" for r in all_days) or "- No sessions yet"

    content = f"""---
type: master-index
last_updated: {date.today()}
tags: [datacharizard, index]
---

# 🔥 DataCharizard — Master Index

## Stats
| Metric | Value |
|--------|-------|
| Level | {level} |
| Total XP | {xp} |
| Lessons completed | {total_lessons} |
| Quiz questions | {total_quizzes} |
| Quiz accuracy | {accuracy}% |

## Daily sessions
{day_links}

## Topics
- [[lessons/]] — browse all lesson notes
"""
    path = os.path.join(OBSIDIAN_VAULT, "DataCharizard Index.md")
    with open(path, "w") as f:
        f.write(content)
    print(f"  📓 Master index updated.")
